on: push
jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
    - name: Greet
      run: echo Hello world linux
  job2:
    runs-on: windows-2019
    steps:
    - name: Greet
      run: echo Hello world linux
